import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        {/* Header */}
        <header className="h-14 flex items-center pl-12 md:pl-24 pr-8 bg-primaryDark text-white">
          <nav>
            <h1 className="text-lg font-bold">BROCOLLI & CO.</h1>
          </nav>
        </header>

        {/* Main Content */}
        <main className="flex-1 px-8 bg-primaryLight">{children}</main>

        {/* Footer */}
        <footer className="h-14 w-full px-8 bg-primaryDark text-white flex items-center justify-center">
          <div className="flex flex-col text-sm items-center">
            <a
              href="https://www.paulpatena.com"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline"
            >
              &copy; 2024 Paul Patena
            </a>
            <span>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
